      - job: build_app
        displayName: Build Serverless Deployment Package
        pool:
          vmImage: ubuntu-16.04
        steps:

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.7'
              addToPath: true
            displayName: Install Python

          - task: NodeTool@0
            inputs:
              versionSpec: '>10.x.x'
            displayName: Install Node

          - bash: npm install -no-cache
            displayName: Install Serverless Dependencies and Plugins

          - task: AWSShellScript@1
            inputs:
              awsCredentials: 'dev'
              regionName: 'eu-central-1'
              scriptType: 'inline'
              inlineScript: |
                                ./node_modules/.bin/serverless package --stage dev --region eu-central-1 --package /tmp/dev_artifacts/
            displayName: Package for Dev Environment

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: /tmp/dev_artifacts
              artifactName: dev_artifacts
            displayName: Export Dev Artifacts