trigger: none

variables:
- group: image-build

jobs:
- job: s3_to_azureblob
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:

  - bash: |
          sudo apt update -y
          sudo apt install awscli -y 
  - bash: |
          sudo aws --version
  - bash: |
          sudo aws s3 ls

    env:
      aws_access_key_id: $(aws_access_key_id)
      aws_secret_access_key: $(aws_secret_access_key)