trigger: none

pr:
  autoCancel: true
  branches:
   include: 
   - master
  paths:
   exclude:
   - README.adoc
   - Vagrantfile
   - common/scripts/ansible/runner.yml
   - scripts/9-install-ansible.sh
   - common/scripts/ansible/common.yml
   - variables-pipeline-runner.json
   - pipeline-pr-runner.yml
   - pipeline-merge-runner.yml

variables:
- group: vault-packer-stage-build

jobs:
- job: build_vault
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
  - task: riezebosch.Packer.PackerTool.PackerTool@0
    displayName: 'Use Packer'
    inputs:
      version: $(PACKER_VERSION)

  - bash: |
          sudo apt update -y
          sudo apt install -y ruby ruby-dev libffi-dev build-essential
          sudo gem install rake inspec-bin ed25519 bcrypt_pbkdf --no-document inspec-bin --source https://artifacts.pwc.com/artifactory/api/gems/gems-remote
  
  - bash: |
          sudo apt install jq -y

  - bash: |
          inspec check $(system.defaultWorkingDirectory)/tests/local/common --chef-license=accept-silent

  - bash: |
          packer validate --syntax-only $(system.defaultWorkingDirectory)/build.json

  - bash: |
          cd $(system.defaultWorkingDirectory)
          packer build \
          -only="Vault Image" \
          --var-file=./stage-variables-pipeline.json \
          -var "git_ref=$(git rev-parse --abbrev-ref HEAD)" \
          -var "git_commit_hash=$(git rev-parse HEAD)" \
          -var "git_short_commit_hash=PRTEST-$(git rev-parse --short HEAD)" \
          -var "client_id=$(ARM_CLIENT_ID)" \
          -var "client_secret=$(ARM_CLIENT_SECRET)" \
          -var "build_resource_group_name=$(ARM_RESOURCE_GROUP)" \
          -var "managed_image_resource_group_name=$(ARM_RESOURCE_GROUP)" \
          -var "source_image_subscription=$(SRC_IMG_SUB)" \
          -var "source_image_resource_group=$(SRC_IMG_RG)" \
          -var "source_image_gallery_name=$(SRC_IMG_GALLERY_NAME)" \
          -var "source_image_name=$(SRC_IMG_NAME)" \
          -var "tenant_id=$(TENANT_ID)" \
          -var "sig_replication_regions=$(SIG_REPLICATION_REGIONS)" \
          -var "sig_name=$(SIG_NAME)" \
          -var "dest_pwc_region=$(DEST_PWC_REGION)" \
          build.json 

- job: build_consul
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
  - task: riezebosch.Packer.PackerTool.PackerTool@0
    displayName: 'Use Packer'
    inputs:
      version: $(PACKER_VERSION)

  - bash: |
          sudo apt install -y ruby ruby-dev libffi-dev build-essential
          sudo gem install rake inspec-bin ed25519 bcrypt_pbkdf --no-document inspec-bin --source https://artifacts.pwc.com/artifactory/api/gems/gems-remote
  
  - bash: |
          sudo apt install jq -y

  - bash: |
          inspec check $(system.defaultWorkingDirectory)/tests/local/common --chef-license=accept-silent

  - bash: |
          packer validate --syntax-only $(system.defaultWorkingDirectory)/build.json

  - bash: |
          cd $(system.defaultWorkingDirectory)/
          packer build \
          -only="Consul Image" \
          --var-file=./stage-variables-pipeline.json \
          -var "git_ref=$(git rev-parse --abbrev-ref HEAD)" \
          -var "git_commit_hash=$(git rev-parse HEAD)" \
          -var "git_short_commit_hash=stage-$(git rev-parse --short HEAD)" \
          -var "client_id=$(ARM_CLIENT_ID)" \
          -var "client_secret=$(ARM_CLIENT_SECRET)" \
          -var "build_resource_group_name=$(ARM_RESOURCE_GROUP)" \
          -var "managed_image_resource_group_name=$(ARM_RESOURCE_GROUP)" \
          -var "source_image_subscription=$(SRC_IMG_SUB)" \
          -var "source_image_resource_group=$(SRC_IMG_RG)" \
          -var "source_image_gallery_name=$(SRC_IMG_GALLERY_NAME)" \
          -var "source_image_name=$(SRC_IMG_NAME)" \
          -var "tenant_id=$(TENANT_ID)" \
          -var "sig_replication_regions=$(SIG_REPLICATION_REGIONS)" \
          -var "sig_name=$(SIG_NAME)" \
          -var "dest_pwc_region=$(DEST_PWC_REGION)" \
          build.json

